version: "3"
services:
   web:
      image: nginx:latest
      ports:
       - "8090:80"
      
   database:
      image: mysql:8.0
      environment:
       MYSQL_ROOT_PASSWORD: root
   java:
     image: myjavaimage