apiVersion: v1
kind: Service
metadata:
  name: restdemo-service
  namespace: k8sdemo
spec:
  selector:
    app: restdemo
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer